source-dir: '/var/www/config/sync'
rules:

  # Exclude some file off the process.
  - description: 'Ignore file'
    match:
      - '/^core\.extension\.yml$/'
      - '/^update\.settings\.yml$/'
      # Do not process language related files.
      - '/^language\//'
    actions:
      skip: ~

  # Remove some unexpected Yaml attributes.
  - description: 'Remove unexpected attributes from YAML data'
    actions:
      remove-props:
        props:
          - uuid
          - _core

  # Copy some files to OMAE profile config/install.new dir
  - description: 'Copy to omae profile'
    match:
      # Liste des blocs customs à exporter
      - '/^block\.block\.blocintegrezlacommunaute\.yml$/'
      - '/^block\.block\.cartelogements\.yml$/'
      # Liste des blocs views
      - '/^block\.block\.views_block__actualites_block_1\.yml$/'
      - '/^block\.block\.views_block__conseils_astuces_block_1\.yml$/'
      - '/^block\.block\.views_block__faqs_block_1\.yml$/'
      - '/^block\.block\.views_block__temoignages_block_1\.yml$/'
      # Liste des blocs du thème omae
      - '/^block\.block\.omae_theme_[^\.]+\.yml$/'
      - '/\.conseil_astuce\./'
      - '/\.conseils_astuces\./'
    actions:
      save :
        dest: '/var/www/public/profiles/custom/omae/config/install.new'
      skip: ~

  # Copy some files to common profile config/install.new dir
  - description: 'Copy to common profile'
    actions:
      save:
        dest: '/var/www/local-dev-depencencies/chalets_base/config/install.new'
